image: golang:1.15-alpine

stages:
  - build
  - image

variables:
  DOCKER_DRIVER: overlay2

compile:
  stage: build
  script:
    - go version
    - go mod download
    - if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi;
    - go vet
    - go test
    - CGO_ENABLED=0 go build -o yarn-prometheus-exporter .
  artifacts:
    name: "artifact_{$CI_COMMIT_SHA}"
    expire_in: 30 min
    paths:
      - yarn-prometheus-exporter
      - Dockerfile

build-docker:
  stage: image
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - mkdir -p $HOME/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - if [ "${CI_COMMIT_REF_SLUG}" == "master" ]; then IMAGE_TAG="latest"; else IMAGE_TAG="${CI_COMMIT_REF_SLUG}"; fi
    - docker build --pull -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  dependencies:
    - compile
  variables:
    GIT_STRATEGY: none
  tags:
    - docker-images

